# Generated by Django 4.2.3 on 2023-07-06 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_contact', models.CharField(max_length=20)),
                ('emp_role', models.CharField(max_length=200)),
                ('emp_salary', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
